spring.profiles.active: develop
server:
  port: 8090
---
spring:
  profiles: develop
  jpa:
    show_sql: false
    database: H2
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driverClassName: org.h2.Driver
    initialize: false
  h2:
    console:
      enabled: true

stripe.simulator.charges-uri: https://sandbox.playtomic.io/v1/stripe-simulator/charges
stripe.simulator.refunds-uri: https://sandbox.playtomic.io/v1/stripe-simulator/payments/{payment_id}/refunds

---
spring:
  profiles: test
  jpa:
    show_sql: false
    database: H2
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driverClassName: org.h2.Driver
    initialize: false
  h2:
    console:
      enabled: true

stripe.simulator.charges-uri: https://sandbox.playtomic.io/v1/stripe-simulator/charges
stripe.simulator.refunds-uri: https://sandbox.playtomic.io/v1/stripe-simulator/payments/{payment_id}/refunds